### ISSUE TITLE
Refactor: Support Ebean 9.3.1 with ElasticSearch only support (comes with move to Java8)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-elastic#18]
Update ebean-elastic to support ElasticSearch only use (no DB required).

**Comment by icode** [comment]
And #3 support is important. Because most do not use the database when using local or embedded `es`, such as nexus oss 3.x https://github.com/sonatype/nexus-public/blob/master/components/nexus-repository/src/main/java/org/sonatype/nexus/repository/search/SearchServiceImpl.java

And do not use the `es` cluster, there is performance overhead when using http access
